title: LAGraph
description: Documentation and Information About LAGraph
baseurl: "/www" # the subpath of your site, e.g. /blog
url: "https://graphblas.github.io/LAGraph-Website"

remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true
