title: LAGraph
description: Documentation and Information About LAGraph
url: "https://graphblas.github.io/LAGraph-Website"

remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true
